### ISSUE TITLE
Fall back to OpenNIC if not found on djdns and the TLD is an OpenNIC TLD

### ISSUE THREAD

**Issue by thefinn93** [MaddieM4/djdns-hype-flat#3]
DJDNS now falls back to Google if it can't find the domain. It should fall back to [OpenNIC](http://www.opennicproject.org/) for `.bbs`, `.dyn`, `.free`, `.fur`, `.geek`, `.gopher`, `.indy`, `.ing`, `.mirco`, `.neo`, `.null`, `.oss`, `.oz`, and `.parody`. A full list of OpenNIC servers can be found [here](http://wiki.opennicproject.org/Tier2)

**Comment by MaddieM4** [comment]
Sounds good. I'll work on this tomorrow - it's a simple change in theory, but I'm pretty sleepy.

I'll let you know when it's pushed so we can verify that it's getting pushed to finnbot.
