### ISSUE TITLE
Domain request

### ISSUE THREAD

**Issue by dansup** [MaddieM4/djdns-hype-flat#4]
I'd like to request some domains that exist already on Hyperboria, I'd like to forward them to the existing sites and make them compatible. I can verify ownership of each ICANN domain if necessary.

appnode.hype
gitboria.hype
hypeirc.hype
hyperboria.hype
projectmeshnet.hype
socialnode.hype
urlcloud.hype

**Comment by MaddieM4** [comment]
I'll get on this in the morning. If you could verify ownership, that would
be really awesome.

**Comment by dansup** [comment]
http://hypeirc.net/verify.html
http://hyperboria.net/verify.html
https://projectmeshnet.org/verify.html
http://socialno.de/verify.html
http://urlcloud.net/verify.html

I can verify Appnode/Gitboria another time .

**Comment by MaddieM4** [comment]
I have a pull request in #6. Let me know if there are any IP addresses that are missing, I pulled together everything I could find.

**Comment by dansup** [comment]
Everything looks good, I have recently updated appno.de to point towards fcbf:7bbc:32e4:716:bd00:e936:c927:fc14. Would it be possible to change 000c to fc14? Appreciate this, thanks!

**Comment by MaddieM4** [comment]
Fix is in the branch. Let me know as soon as you approve this, so I can merge and deploy. Sorry about the crazy latency, my life is suddenly a lot busier than I'm at all equipped to deal with.

**Comment by dansup** [comment]
Looks great. Thanks again!

**Comment by MaddieM4** [comment]
[Deployed :D](http://projectmeshnet.hype/)
