### ISSUE TITLE
Webhook for #radar

### ISSUE THREAD

**Issue by thefinn93** [MaddieM4/djdns-hype-flat#5]
Please add the following URL as [a web hook for this repo](https://github.com/campadrenalin/djdns-hype-flat/settings/hooks):

`http://thefinn93.com:8080/github/`

**Comment by MaddieM4** [comment]
I recall that last time there was a list that I added the repos to. I take it you'll handle adding this project to the list when I'm done?

**Comment by MaddieM4** [comment]
Actually, I just checked, and I already have a web hook set up for this repo and that announce URL. If my commits aren't showing up in #radar, it's not for lack of setup.

**Comment by thefinn93** [comment]
Yep, I checked the list and it says it's already on ther, but I haven't
been seeing announcements

Finn Herzfeld

**Comment by thefinn93** [comment]
Alright, thanks

**Comment by MaddieM4** [comment]
Very strange. Ah well. I'm making a mental note to pay attention about this next time I push a commit.
